# Important: note how we use the branch name as Image name AND as the Service name - eg pocket-demo-1

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/bedrock-demo/${BRANCH_NAME}',   # Branch name is image name
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/bedrock-demo/${BRANCH_NAME}',  # Branch name is image name
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${BRANCH_NAME}'  # Branch name is the Service name
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/bedrock-demo/${BRANCH_NAME}'  # Branch name is image name
      - '--env-vars-file=/workspace/gcp/bedrock-demos/cloudrun/pocket-demo.env.yaml' # Pocket-specific demo env vars
      - --update-secrets=BASKET_API_KEY=bedrock-demos-core-BASKET_API_KEY:latest,SECRET_KEY=bedrock-demos-core-SECRET_KEY:latest,FXA_ENDPOINT=bedrock-demos-core-FXA_ENDPOINT:latest,VPN_ENDPOINT=bedrock-demos-core-VPN_ENDPOINT:latest  # NB all one line, no spaces
      - '--allow-unauthenticated'
      - '--region=us-central1'
      - '--max-instances=10'


timeout: 2400s # Typical build takes around 17 minutes, so 40min max should be plenty
